version: "2"
services:
    reverse-proxy:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/www:/www
        ports:
            - 80:80
            - 443:443
    
    api:
        image: node:lts
        volumes:
            - ./express:/express
        entrypoint: /express/start.sh